name: Deploy site with npm

on:
  # Runs on pushes to the default branch
  push:
    branches:
      - master # Or master, depending on your repository

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetches the theme as a submodule

      - name: Setup Node.js
        # Sets up the node environment to run npm commands
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a recent stable version of Node.js
          cache: 'npm'       # Caches npm dependencies for faster builds

      - name: Install dependencies
        # Use "npm install" because there is no package-lock.json
        run: npm install
      
      - name: Install Hugo
        # We still need Hugo itself, let's install it using a setup action
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build the site
        # Runs the build script defined in package.json
        run: npm run build

      - name: Upload artifact
        # Gathers the build output for the deployment job
        uses: actions/upload-pages-artifact@v3
        with:
          # The output from 'npm run build' will be in 'exampleSite/public'
          path: ./exampleSite/public

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
